/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "inverse-primary": "#c9c6c5",
        "surface": "#fdf8f8",
        "on-tertiary-container": "#868381",
        "surface-dim": "#ddd9d8",
        "brand-peach": "#ffb084",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#e6e1df",
        "primary-fixed-dim": "#c9c6c5",
        "outline-variant": "#c4c7c7",
        "brand-coral": "#ff6b5a",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "surface-tint": "#5f5e5e",
        "brand-teal": "#1a3a3a",
        "background": "#fffaf0",
        "canvas": "#fffaf0",
        "brand-mint": "#a4d4c5",
        "on-secondary-fixed": "#1d1c16",
        "secondary": "#615e57",
        "secondary-container": "#e7e2d8",
        "surface-soft": "#faf5e8",
        "inverse-surface": "#313030",
        "surface-container-highest": "#e5e2e1",
        "tertiary-container": "#1d1b1a",
        "primary-fixed": "#e5e2e1",
        "brand-pink": "#ff4d8b",
        "surface-bright": "#fdf8f8",
        "surface-container": "#f1edec",
        "hairline": "#e5e5e5",
        "brand-lavender": "#b8a4ed",
        "tertiary": "#000000",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#474646",
        "secondary-fixed-dim": "#cac6bd",
        "on-primary-fixed": "#1c1b1b",
        "secondary-fixed": "#e7e2d8",
        "tertiary-fixed-dim": "#cac6c3",
        "on-surface": "#1c1b1b",
        "inverse-on-surface": "#f4f0ef",
        "primary-container": "#1c1b1b",
        "on-secondary-fixed-variant": "#494740",
        "surface-container-high": "#ebe7e6",
        "surface-container-lowest": "#ffffff",
        "body-muted": "#6a6a6a",
        "on-error-container": "#93000a",
        "on-primary-container": "#858383",
        "on-tertiary-fixed": "#1d1b1a",
        "on-background": "#1c1b1b",
        "error": "#ba1a1a",
        "surface-strong": "#ebe6d6",
        "surface-card": "#f5f0e0",
        "surface-container-low": "#f7f3f2",
        "on-secondary-container": "#67645d",
        "primary": "#0a0a0a",
        "brand-ochre": "#e8b94a",
        "on-tertiary-fixed-variant": "#484645",
        "outline": "#747878",
        "on-surface-variant": "#444748",
        "surface-variant": "#e5e2e1",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px",
      },
      spacing: {
        "base": "4px",
        "xs": "8px",
        "sm": "12px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "xxl": "48px",
        "section": "96px",
        "container-max": "1280px",
      },
      fontFamily: {
        "display": ["Rubik", "sans-serif"],
        "display-xl-mobile": ["Rubik", "sans-serif"],
        "label-uppercase": ["Inter", "sans-serif"],
        "display-sm": ["Rubik", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "display-md": ["Rubik", "sans-serif"],
        "display-xl": ["Rubik", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "display-lg": ["Rubik", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "button": ["Inter", "sans-serif"],
        "sans": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-xl-mobile": ["36px", { lineHeight: "1.1", letterSpacing: "-1px", fontWeight: "500" }],
        "label-uppercase": ["12px", { lineHeight: "1.4", letterSpacing: "1.5px", fontWeight: "600" }],
        "display-sm": ["32px", { lineHeight: "1.15", letterSpacing: "-0.5px", fontWeight: "500" }],
        "title-lg": ["24px", { lineHeight: "1.3", letterSpacing: "-0.3px", fontWeight: "600" }],
        "display-md": ["40px", { lineHeight: "1.1", letterSpacing: "-1px", fontWeight: "500" }],
        "display-xl": ["72px", { lineHeight: "1.0", letterSpacing: "-2.5px", fontWeight: "500" }],
        "title-md": ["18px", { lineHeight: "1.4", fontWeight: "600" }],
        "display-lg": ["56px", { lineHeight: "1.05", letterSpacing: "-2px", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "1.55", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.55", fontWeight: "400" }],
        "button": ["14px", { lineHeight: "1.0", fontWeight: "600" }],
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-15px)" },
        },
        pulseGlow: {
          "0%, 100%": { opacity: "0.2" },
          "50%": { opacity: "0.4" },
        },
      },
      animation: {
        float: "float 6s ease-in-out infinite",
        pulseGlow: "pulseGlow 4s ease-in-out infinite",
      },
    },
  },
  plugins: [],
}
