export const supplierWires = [
  {
    id: 'apex-textiles',
    legal_name: 'Apex Sustainable Textiles Manufacturing Co., Ltd.',
    trade_name: 'Apex Textiles Ltd.',
    location: 'Bangkok, Southeast Asia',
    region: 'Asia Pacific',
    category: 'Textiles',
    description: 'Premium organic cotton and sustainable fabric manufacturer based in Southeast Asia with zero-water waste dyeing technology.',
    capacity: '120,000 meters / month',
    moq: '500 units',
    lead_time: '14-21 Days',
    rating: 4.9,
    reviews_count: 128,
    theme_color: 'brand-teal',
    avatar_initial: 'A',
    listing_state: 'listed',
    trust: {
      band: 'verified',
      method: 'registry_and_audit',
      method_label: 'Registry check & facility audit',
      verified_at: '2026-08-10T09:00:00Z',
      valid_until: '2027-02-10T09:00:00Z',
      last_checked: '3 days ago',
      overall_score: 94,
      pillars: [
        ['Identity', 96],
        ['Legal', 92],
        ['Quality', 95],
        ['Capability', 91],
      ],
      gates_applied: [],
    },
    claims: [
      { key: 'business_license', label: 'Commercial Business Registration', value: 'REG-TH-98214-BKK', state: 'verified', method: 'third_party_api', method_label: 'Registry API check', verified_at: '2026-08-10T09:00:00Z', valid_until: '2027-08-10T09:00:00Z', evidence_count: 2 },
      { key: 'gots_cert', label: 'Global Organic Textile Standard (GOTS)', value: 'GOTS-2025-CU-8834', state: 'verified', method: 'document_review', method_label: 'Accredited auditor review', verified_at: '2026-06-15T09:00:00Z', valid_until: '2027-06-14T09:00:00Z', evidence_count: 3 },
      { key: 'iso_9001', label: 'ISO 9001:2015 Quality Management', value: 'Cert #ISO-TH-44910', state: 'verified', method: 'document_review', method_label: 'Third-party auditor check', verified_at: '2026-05-20T09:00:00Z', valid_until: '2027-05-19T09:00:00Z', evidence_count: 4 },
      { key: 'labor_standards', label: 'Fair Labor & BSCI Compliance Audit', value: 'Grade A rating (Score 98/100)', state: 'verified', method: 'site_audit', method_label: 'On-site facility inspection', verified_at: '2026-07-05T09:00:00Z', valid_until: '2027-07-04T09:00:00Z', evidence_count: 5 },
      { key: 'production_capacity', label: 'Audited monthly weaving capacity', value: '120,000 meters / month', state: 'verified', method: 'site_audit', method_label: 'Physical engineering verification', verified_at: '2026-07-05T09:00:00Z', valid_until: '2027-07-04T09:00:00Z', evidence_count: 2 },
    ],
  },
  {
    id: 'ecopack-solutions',
    legal_name: 'EcoPack Circular Packaging Solutions GmbH',
    trade_name: 'EcoPack Solutions',
    location: 'Berlin, Germany',
    region: 'Europe',
    category: 'Packaging',
    description: 'Biodegradable and compostable packaging materials engineered for modern FMCG and direct-to-consumer brands.',
    capacity: '450,000 units / month',
    moq: '1,000 units',
    lead_time: '7-10 Days',
    rating: 4.7,
    reviews_count: 84,
    theme_color: 'brand-pink',
    avatar_initial: 'E',
    listing_state: 'listed',
    trust: {
      band: 'verified',
      method: 'third_party_api',
      method_label: 'EU Registry & EN 13432 Certification',
      verified_at: '2026-08-12T14:30:00Z',
      valid_until: '2026-12-12T14:30:00Z',
      last_checked: '1 week ago',
      overall_score: 91,
      pillars: [
        ['Identity', 98],
        ['Legal', 94],
        ['Quality', 89],
        ['Capability', 85],
      ],
      gates_applied: [],
    },
    claims: [
      { key: 'eu_vat', label: 'EU VAT & Commercial Register', value: 'DE 309 881 294 (HRB 19283)', state: 'verified', method: 'third_party_api', method_label: 'VIES Automated verification', verified_at: '2026-08-12T14:30:00Z', valid_until: '2027-08-12T14:30:00Z', evidence_count: 2 },
      { key: 'compostable_cert', label: 'TÜV Austria EN 13432 Compost Home', value: 'Certificate #TA-8829-OK-COMPOST', state: 'verified', method: 'document_review', method_label: 'Certification body cross-check', verified_at: '2026-06-01T09:00:00Z', valid_until: '2027-06-01T09:00:00Z', evidence_count: 3 },
      { key: 'fsc_cert', label: 'FSC Chain of Custody (FSC-C12389)', value: 'Verified 100% Recycled content', state: 'verified', method: 'third_party_api', method_label: 'FSC public database query', verified_at: '2026-07-18T09:00:00Z', valid_until: '2027-07-18T09:00:00Z', evidence_count: 2 },
      { key: 'stated_lead_time', label: 'Standard production turnaround', value: '7-10 Days', state: 'under_review', method: 'self_declared', method_label: 'Supplier declaration pending verification', verified_at: null, valid_until: null, evidence_count: 1 },
    ],
  },
  {
    id: 'nova-electronics',
    legal_name: 'Nova Precision Microelectronics Corporation Ltd.',
    trade_name: 'Nova Electronics',
    location: 'Shenzhen, Guangdong, CN',
    region: 'Asia Pacific',
    category: 'Electronics',
    description: 'High-precision electronic components, SMT placement, and PCB assembly services for IoT hardware.',
    capacity: '60,000 boards / month',
    moq: '100 units',
    lead_time: '30-45 Days',
    rating: 4.2,
    reviews_count: 32,
    theme_color: 'brand-ochre',
    avatar_initial: 'N',
    listing_state: 'listed',
    trust: {
      band: 'basic',
      method: 'document_review',
      method_label: 'Business license verified; quality pending audit',
      verified_at: '2026-07-20T08:00:00Z',
      valid_until: '2026-10-20T08:00:00Z',
      last_checked: '3 weeks ago',
      overall_score: 68,
      pillars: [
        ['Identity', 82],
        ['Legal', 75],
        ['Quality', 48],
        ['Capability', 65],
      ],
      gates_applied: ['Facility audit report pending re-submission'],
    },
    claims: [
      { key: 'business_id', label: 'Unified Social Credit Identifier', value: '91440300MA5EX7689B', state: 'verified', method: 'third_party_api', method_label: 'NECIPS Registry Check', verified_at: '2026-07-20T08:00:00Z', valid_until: '2027-07-20T08:00:00Z', evidence_count: 2 },
      { key: 'rohs_reach', label: 'RoHS & REACH Compliance Declaration', value: 'Self-declaration with lab test reports', state: 'under_review', method: 'document_review', method_label: 'Verifier document examination', verified_at: null, valid_until: null, evidence_count: 2 },
      { key: 'iso_9001', label: 'ISO 9001:2015 Certification', value: 'Awaiting updated certificate upload', state: 'submitted', method: 'self_declared', method_label: 'Self-declared by supplier', verified_at: null, valid_until: null, evidence_count: 1 },
    ],
  },
  {
    id: 'acme-corp-global',
    legal_name: 'Acme Advanced Industrial Technologies Global Inc.',
    trade_name: 'Acme Corp Global',
    location: 'Chicago, Illinois, US',
    region: 'North America',
    category: 'Machining',
    description: 'Tier-1 precision CNC machining, aerospace tooling, and medical-grade robotic component manufacturing.',
    capacity: '200,000 components / month',
    moq: '250 units',
    lead_time: '10-15 Days',
    rating: 4.8,
    reviews_count: 210,
    theme_color: 'brand-lavender',
    avatar_initial: 'A',
    listing_state: 'listed',
    trust: {
      band: 'audited',
      method: 'comprehensive_audit',
      method_label: 'Full D&B integration, AS9100D & on-site audit',
      verified_at: '2026-08-20T11:00:00Z',
      valid_until: '2027-08-20T11:00:00Z',
      last_checked: 'Yesterday',
      overall_score: 96,
      pillars: [
        ['Identity', 99],
        ['Legal', 97],
        ['Quality', 98],
        ['Capability', 93],
      ],
      gates_applied: [],
    },
    claims: [
      { key: 'duns_number', label: 'Dun & Bradstreet D-U-N-S® Registration', value: '08-112-9921 (Risk Rating: 1 - Minimal)', state: 'verified', method: 'third_party_api', method_label: 'D&B Live API sync', verified_at: '2026-08-20T11:00:00Z', valid_until: '2027-08-20T11:00:00Z', evidence_count: 4 },
      { key: 'as9100', label: 'AS9100D / ISO 9001:2015 Aerospace Certification', value: 'OASIS Certified #AS-88192-US', state: 'verified', method: 'third_party_api', method_label: 'IAQG OASIS live check', verified_at: '2026-08-15T09:00:00Z', valid_until: '2027-08-14T09:00:00Z', evidence_count: 3 },
      { key: 'itar_registered', label: 'ITAR Directorate of Defense Trade Controls', value: 'DDTC Reg #M39182', state: 'verified', method: 'document_review', method_label: 'Federal registration cross-check', verified_at: '2026-07-10T09:00:00Z', valid_until: '2027-07-09T09:00:00Z', evidence_count: 2 },
      { key: 'esg_ecovadis', label: 'EcoVadis Sustainability Gold Medal', value: 'Score: 78/100 (Top 5th percentile)', state: 'verified', method: 'third_party_api', method_label: 'EcoVadis API Integration', verified_at: '2026-08-01T09:00:00Z', valid_until: '2027-08-01T09:00:00Z', evidence_count: 3 },
    ],
  },
  {
    id: 'aravind-fasteners',
    legal_name: 'Aravind Precision Fasteners Private Limited',
    trade_name: 'Aravind Fasteners',
    location: 'Ludhiana, Punjab, IN',
    region: 'India',
    category: 'Industrial fasteners',
    description: 'High-tensile industrial fasteners, custom cold-forged bolts, studs, and automotive hardware components.',
    capacity: '80,000 units / month',
    moq: '2,000 units',
    lead_time: '14 days',
    rating: 4.8,
    reviews_count: 96,
    theme_color: 'brand-teal',
    avatar_initial: 'A',
    listing_state: 'listed',
    trust: {
      band: 'verified',
      method: 'third_party_api',
      method_label: 'GST Portal & ISO Registrar Registry Checks',
      verified_at: '2026-08-15T09:00:00Z',
      valid_until: '2026-11-15T09:00:00Z',
      last_checked: '4 days ago',
      overall_score: 88,
      pillars: [
        ['Identity', 92],
        ['Legal', 86],
        ['Quality', 68],
        ['Capability', 58],
      ],
      gates_applied: [],
    },
    claims: [
      { key: 'gst_registration', label: 'GST registration', value: '03AAECA9082G1ZP', state: 'verified', method: 'third_party_api', method_label: 'GSTN Government Registry API', verified_at: '2026-08-15T09:00:00Z', valid_until: '2026-11-15T09:00:00Z', evidence_count: 2 },
      { key: 'iso_9001', label: 'ISO 9001:2015 Quality Management', value: 'Certificate #QMS-IND-2024-9182', state: 'verified', method: 'document_review', method_label: 'Accredited verifier audit', verified_at: '2026-07-28T09:00:00Z', valid_until: '2027-03-30T09:00:00Z', evidence_count: 3 },
      { key: 'annual_capacity', label: 'Stated production capacity', value: '80,000 units / month', state: 'under_review', method: 'self_declared', method_label: 'Self-declaration pending verification', verified_at: null, valid_until: null, evidence_count: 1 },
    ],
  },
  {
    id: 'monarch-industrial',
    legal_name: 'Monarch Industrial Components LLP',
    trade_name: 'Monarch Industrial',
    location: 'Rajkot, Gujarat, IN',
    region: 'India',
    category: 'Precision machined parts',
    description: 'Custom CNC turned and milled brass, aluminum, and stainless steel fittings for industrial machinery.',
    capacity: '35,000 components / month',
    moq: '500 units',
    lead_time: '21 days',
    rating: 4.4,
    reviews_count: 47,
    theme_color: 'brand-peach',
    avatar_initial: 'M',
    listing_state: 'listed',
    trust: {
      band: 'basic',
      method: 'document_review',
      method_label: 'GST verified; Quality evidence partial',
      verified_at: '2026-07-02T09:00:00Z',
      valid_until: '2026-10-02T09:00:00Z',
      last_checked: '7 weeks ago',
      overall_score: 62,
      pillars: [
        ['Identity', 74],
        ['Legal', 57],
        ['Quality', 18],
        ['Capability', 26],
      ],
      gates_applied: ['Quality evidence is incomplete'],
    },
    claims: [
      { key: 'gst_registration', label: 'GST registration', value: '24AAXFM9104Q1ZN', state: 'verified', method: 'third_party_api', method_label: 'GSTN API Registry', verified_at: '2026-07-02T09:00:00Z', valid_until: '2026-10-02T09:00:00Z', evidence_count: 2 },
      { key: 'quality_management', label: 'Quality management process', value: 'Self-declared inspection procedure', state: 'under_review', method: 'self_declared', method_label: 'Awaiting third-party calibration logs', verified_at: null, valid_until: null, evidence_count: 1 },
    ],
  },
  {
    id: 'narmada-fabrication',
    legal_name: 'Narmada Advanced Custom Fabrication and Integrated Industrial Solutions Private Limited',
    trade_name: 'Narmada Fabrication',
    location: 'Indore, Madhya Pradesh, IN',
    region: 'India',
    category: 'Sheet-metal fabrication',
    description: 'Heavy duty laser cutting, press brake bending, and robotic MIG/TIG welded assemblies for construction and agriculture.',
    capacity: 'On request',
    moq: '100 units',
    lead_time: '28 days',
    rating: 3.9,
    reviews_count: 14,
    theme_color: 'brand-coral',
    avatar_initial: 'N',
    listing_state: 'listed',
    trust: {
      band: 'unverified',
      method: 'self_declared',
      method_label: 'Supplier assertion, pending verification',
      verified_at: '2026-08-18T09:00:00Z',
      valid_until: null,
      last_checked: 'Supplier assertion, 1 day ago',
      overall_score: 28,
      pillars: [
        ['Identity', 12],
        ['Legal', 0],
        ['Quality', 15],
        ['Capability', 22],
      ],
      gates_applied: ['Identity has not been independently established', 'No verified physical location check'],
    },
    claims: [
      { key: 'gst_registration', label: 'GST registration', value: 'Supplier-submitted identifier', state: 'under_review', method: 'self_declared', method_label: 'Registry verification in progress', verified_at: null, valid_until: null, evidence_count: 1 },
      { key: 'factory_capacity', label: 'Factory capacity', value: 'On request', state: 'submitted', method: 'self_declared', method_label: 'Self-declared assertion', verified_at: null, valid_until: null, evidence_count: 1 },
    ],
  },
]

export const verificationTaskWires = [
  {
    id: 'VT-1084',
    supplier_id: 'aravind-fasteners',
    claim_key: 'annual_capacity',
    claim_label: 'Stated production capacity (80,000 units/mo)',
    state: 'in_review',
    priority: 'High',
    assigned_to: 'Sarah Jenkins',
    sla: 'Due in 2h 18m',
    evidence_count: 2,
    evidence_summary: 'Factory floor machinery manifest & power consumption utility bills (July 2026)',
    submitted_at: '2026-08-25T10:14:00Z',
  },
  {
    id: 'VT-1081',
    supplier_id: 'monarch-industrial',
    claim_key: 'quality_management',
    claim_label: 'Quality management process & calibration',
    state: 'awaiting_supplier',
    priority: 'Normal',
    assigned_to: 'R. Kapoor',
    sla: 'Awaiting evidence',
    evidence_count: 1,
    evidence_summary: 'Internal SOP document uploaded; awaiting external calibration certificates',
    submitted_at: '2026-08-22T08:30:00Z',
  },
  {
    id: 'VT-1077',
    supplier_id: 'narmada-fabrication',
    claim_key: 'gst_registration',
    claim_label: 'Legal entity GST registration',
    state: 'queued',
    priority: 'High',
    assigned_to: 'Unassigned',
    sla: 'Due today',
    evidence_count: 1,
    evidence_summary: 'Scanned GST certificate (03AAECA9082G1ZP)',
    submitted_at: '2026-08-25T16:45:00Z',
  },
  {
    id: 'VT-1092',
    supplier_id: 'nova-electronics',
    claim_key: 'rohs_reach',
    claim_label: 'RoHS & REACH Lab Test Reports',
    state: 'in_review',
    priority: 'Normal',
    assigned_to: 'Alex Wong',
    sla: 'Due tomorrow',
    evidence_count: 3,
    evidence_summary: 'SGS test reports for PCB substrate materials and lead-free solder paste',
    submitted_at: '2026-08-24T14:10:00Z',
  },
]
